### ISSUE TITLE
Fan speed always at 0

### ISSUE THREAD

**Issue by poudenes** [oldhui-uk/tftbridge#3]
Hi There,

Would be nice to test things to make this great script complete.

The Fan speed says 0%. This does not change also when I change it in klipper

**Comment by StarNamer** [comment]
The TFT35 firmware assumes that the printer is running Marlin and send several G-codes to get information many of which aren't implemented by Klipper.

From looking at the TFT35 code (I've submitted some changes in the past, so have a copy on my PC already), the fan query appears to use M710, which isn't implemented in Klipper. It may be possible to write a macro for it, but otherwise, the TFT35 gets no response, so stays stuck at 0%.

**Comment by StarNamer** [comment]
OK, once I looked at the code I remembered working on the TFT35 and Marlin codes to get the fan display working a few years ago. I submitted some PRs which were discussed, but I don't think my exact solution was implemented.

As I recall, the issue is that both the PC/RPi running Octoprint (usually) via USB and the TFT35 are 'hosts' talking to the printer controller. The issue then was that the fan display only updated if the TFT35 sent the M106 command as it didn't look for a response (there wasn't one) and simply took the value set; Octoprint was sent a response so updated whether the command came from RPi or TFT35. The solution was to echo response to all hosts (both USB and RS232) whichever sent the command. I've looked at the recent Marlin code and assume it does the same thing, though it's been rewritten.

The way TftBridge works is to simulate console commands and many of them give no response or a simple 'ok'. So it may require Klipper modification to get this to work although a macro replacing M106 might be able to do it if the right response can be sent. However, my initial investigation indicates that some responses are suppressed.

If I get time, I'll investigate further as I've like to ee it work.
